// PM2 process config — used on EC2 for production
// Start all services: pm2 start ecosystem.config.js
// Reload (zero-downtime): pm2 reload ecosystem.config.js --update-env

const env = {
  NODE_ENV: "production",
  DATABASE_URL: process.env.DATABASE_URL,
  REDIS_URL: process.env.REDIS_URL || "redis://localhost:6379",
  JENKINS_URL: process.env.JENKINS_URL || "http://localhost:8085",
  JENKINS_USER: process.env.JENKINS_USER || "admin",
  JENKINS_TOKEN: process.env.JENKINS_TOKEN,
  GITHUB_CLIENT_ID: process.env.GITHUB_CLIENT_ID,
  GITHUB_CLIENT_SECRET: process.env.GITHUB_CLIENT_SECRET,
  JWT_SECRET: process.env.JWT_SECRET,
  APP_URL: process.env.APP_URL,
  FRONTEND_URL: process.env.FRONTEND_URL,
  STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
  STRIPE_PUBLISHABLE_KEY: process.env.STRIPE_PUBLISHABLE_KEY,
  STRIPE_PRO_PRICE_ID: process.env.STRIPE_PRO_PRICE_ID,
  STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET,
  OLLAMA_HOST: process.env.OLLAMA_HOST,
  OLLAMA_API_KEY: process.env.OLLAMA_API_KEY,
  OLLAMA_CODE_MODEL: process.env.OLLAMA_CODE_MODEL || "qwen3-coder:480b",
  OLLAMA_STACK_MODEL: process.env.OLLAMA_STACK_MODEL || "qwen3-coder:480b",
  AWS_ACCESS_KEY_ID: process.env.AWS_ACCESS_KEY_ID,
  AWS_SECRET_ACCESS_KEY: process.env.AWS_SECRET_ACCESS_KEY,
  AWS_REGION: process.env.AWS_REGION || "ap-south-1",
  DEPLOY_MODE: process.env.DEPLOY_MODE || "cloud",
  INTERNAL_API_SECRET: process.env.INTERNAL_API_SECRET,
  JENKINS_CALLBACK_SECRET: process.env.JENKINS_CALLBACK_SECRET,
  CORS_ORIGINS: process.env.CORS_ORIGINS,
  AI_SERVICE_URL: process.env.AI_SERVICE_URL || "http://localhost:4005",
};

module.exports = {
  apps: [
    {
      name: "duckops-provisioning",
      script: "dist/index.js",
      cwd: "/opt/duckops/apps/provisioning-service",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "512M",
      env: { ...env, PORT: "4002", PIPELINE_SERVICE_URL: "http://localhost:4003" },
    },
    {
      name: "duckops-pipeline",
      script: "dist/index.js",
      cwd: "/opt/duckops/apps/pipeline-service",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "256M",
      env: { ...env, PORT: "4003" },
    },
    {
      name: "duckops-health",
      script: "dist/index.js",
      cwd: "/opt/duckops/apps/health-service",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "256M",
      env: { ...env, PORT: "4004" },
    },
    {
      name: "duckops-ai",
      script: "dist/index.js",
      cwd: "/opt/duckops/apps/ai-service",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "512M",
      env: { ...env, PORT: "4005", PIPELINE_SERVICE_URL: "http://localhost:4003" },
    },
    {
      name: "duckops-catalog",
      script: "dist/index.js",
      cwd: "/opt/duckops/apps/catalog-service",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "256M",
      env: { ...env, PORT: "4001" },
    },
  ],
};
