import { exec } from "child_process";
import { promisify } from "util";
import fs from "fs/promises";
import path from "path";
import { createLogger } from "@duckops/shared-utils";

const execAsync = promisify(exec);
const logger = createLogger("github-service");

const GITHUB_API = "https://api.github.com";

export interface CreateRepoOptions {
  projectName: string;
  displayName: string;
  description?: string;
  githubUsername: string;
  githubAccessToken: string;
  scaffoldDir: string; // local dir with the generated files
  repoVisibility?: "public" | "private";
}

export interface GitHubRepoResult {
  repoUrl: string;       // https://github.com/user/repo
  repoName: string;      // "my-todo-api"
  repoFullName: string;  // "user/my-todo-api"
  cloneUrl: string;      // https://github.com/user/repo.git
}

// Create a private GitHub repo and push scaffolded code into it
export async function createAndPushRepo(
  opts: CreateRepoOptions,
): Promise<GitHubRepoResult> {
  const { projectName, displayName, description, githubUsername, githubAccessToken, scaffoldDir, repoVisibility = "private" } = opts;
  const isPrivate = repoVisibility !== "public";

  logger.info(`Creating GitHub repo: ${githubUsername}/${projectName} (${repoVisibility})`);

  // 1. Create the repository via GitHub API
  const createRes = await fetch(`${GITHUB_API}/user/repos`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${githubAccessToken}`,
      Accept: "application/vnd.github+json",
      "Content-Type": "application/json",
      "X-GitHub-Api-Version": "2022-11-28",
    },
    body: JSON.stringify({
      name: projectName,
      description: description || `Generated by DuckOps — ${displayName}`,
      private: isPrivate,
      auto_init: false,
    }),
  });

  if (!createRes.ok) {
    const err = (await createRes.json()) as { message?: string };
    // 422 means repo already exists — that's fine, just use it
    if (createRes.status !== 422) {
      throw new Error(`Failed to create GitHub repo: ${err.message || createRes.statusText}`);
    }
    logger.warn(`Repo ${projectName} already exists for ${githubUsername}, reusing it`);
  }

  const repoFullName = `${githubUsername}/${projectName}`;
  const repoUrl = `https://github.com/${repoFullName}`;
  const cloneUrl = `https://github.com/${repoFullName}.git`;

  logger.info(`Repo ready: ${repoUrl}`);

  // 2. Add a .gitignore to the scaffold dir if it doesn't have one
  const gitignorePath = path.join(scaffoldDir, ".gitignore");
  try {
    await fs.access(gitignorePath);
  } catch {
    await fs.writeFile(
      gitignorePath,
      "node_modules\ndist\n.env\n.env.local\n*.log\n",
    );
  }

  // 3. Add a README.md
  const readmePath = path.join(scaffoldDir, "README.md");
  try {
    await fs.access(readmePath);
  } catch {
    await fs.writeFile(
      readmePath,
      `# ${displayName}\n\n${description || "Generated by DuckOps."}\n\n## Getting started\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\`\n`,
    );
  }

  // 4. Git init, commit, and push
  const gitEnv = {
    ...process.env,
    GIT_AUTHOR_NAME: "DuckOps",
    GIT_AUTHOR_EMAIL: "rayansjain29@gmail.com",
    GIT_COMMITTER_NAME: "DuckOps",
    GIT_COMMITTER_EMAIL: "rayansjain29@gmail.com",
  };

  // Never interpolate the token into command strings — pass it via the
  // GIT_ASKPASS / GIT_CONFIG_COUNT mechanism so it never appears in ps output
  // or logs. We set credential.helper to a small inline script.
  const askpassScript = path.join(scaffoldDir, ".git-askpass.sh");

  const run = (cmd: string, extraEnv?: Record<string, string>) =>
    execAsync(cmd, { cwd: scaffoldDir, env: { ...gitEnv, ...extraEnv } });

  // Remove any existing .git dir so we always start fresh
  await fs.rm(path.join(scaffoldDir, ".git"), { recursive: true, force: true });

  await run("git init -b main");
  await run("git add -A");

  // Commit only if there are staged changes
  const { stdout: statusOut } = await execAsync("git status --porcelain", { cwd: scaffoldDir, env: gitEnv });
  if (statusOut.trim()) {
    await run(`git commit -m "Initial scaffold generated by DuckOps"`);
  }

  // Use a credential helper script that echoes the token without exposing it
  // in the command line. The script reads from an env var we pass only to git.
  await fs.writeFile(askpassScript, `#!/bin/sh\necho "$DUCKOPS_GIT_TOKEN"\n`, { mode: 0o700 });
  const credEnv = {
    GIT_ASKPASS: askpassScript,
    DUCKOPS_GIT_TOKEN: githubAccessToken,
  };

  await run(`git remote add origin ${cloneUrl}`, credEnv);

  // Retry push — GitHub repo may not be immediately available on the git server
  // after the API call that created it
  let lastPushError: Error | null = null;
  for (let attempt = 1; attempt <= 5; attempt++) {
    try {
      await run("git push -u origin main --force", credEnv);
      lastPushError = null;
      break;
    } catch (err: any) {
      lastPushError = err;
      logger.warn(`Push attempt ${attempt}/5 failed: ${err.message}. Retrying in ${attempt * 2}s...`);
      await new Promise((r) => setTimeout(r, attempt * 2000));
    }
  }
  // Clean up credential helper regardless of result
  await fs.rm(askpassScript, { force: true });
  if (lastPushError) throw lastPushError;

  logger.info(`Code pushed to: ${repoUrl}`);

  return {
    repoUrl,
    repoName: projectName,
    repoFullName,
    cloneUrl,
  };
}

// Delete a GitHub repo (used when project is deleted)
export async function deleteRepo(
  repoFullName: string,
  githubAccessToken: string,
): Promise<void> {
  const res = await fetch(`${GITHUB_API}/repos/${repoFullName}`, {
    method: "DELETE",
    headers: {
      Authorization: `Bearer ${githubAccessToken}`,
      Accept: "application/vnd.github+json",
      "X-GitHub-Api-Version": "2022-11-28",
    },
  });

  if (!res.ok && res.status !== 404) {
    logger.warn(`Could not delete repo ${repoFullName}: ${res.statusText}`);
  } else {
    logger.info(`Deleted GitHub repo: ${repoFullName}`);
  }
}
