import { exec } from "child_process";
import { promisify } from "util";
import fs from "fs/promises";
import path from "path";
import { createLogger } from "@duckops/shared-utils";

const execAsync = promisify(exec);
const logger = createLogger("github-service");

const GITHUB_API = "https://api.github.com";

export interface CreateRepoOptions {
  projectName: string;
  displayName: string;
  description?: string;
  githubUsername: string;
  githubAccessToken: string;
  scaffoldDir: string; // local dir with the generated files
}

export interface GitHubRepoResult {
  repoUrl: string;       // https://github.com/user/repo
  repoName: string;      // "my-todo-api"
  repoFullName: string;  // "user/my-todo-api"
  cloneUrl: string;      // https://github.com/user/repo.git
}

// Create a private GitHub repo and push scaffolded code into it
export async function createAndPushRepo(
  opts: CreateRepoOptions,
): Promise<GitHubRepoResult> {
  const { projectName, displayName, description, githubUsername, githubAccessToken, scaffoldDir } = opts;

  logger.info(`Creating GitHub repo: ${githubUsername}/${projectName}`);

  // 1. Create the private repository via GitHub API
  const createRes = await fetch(`${GITHUB_API}/user/repos`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${githubAccessToken}`,
      Accept: "application/vnd.github+json",
      "Content-Type": "application/json",
      "X-GitHub-Api-Version": "2022-11-28",
    },
    body: JSON.stringify({
      name: projectName,
      description: description || `Generated by DuckOps — ${displayName}`,
      private: true,
      auto_init: false,
    }),
  });

  if (!createRes.ok) {
    const err = (await createRes.json()) as { message?: string };
    // 422 means repo already exists — that's fine, just use it
    if (createRes.status !== 422) {
      throw new Error(`Failed to create GitHub repo: ${err.message || createRes.statusText}`);
    }
    logger.warn(`Repo ${projectName} already exists for ${githubUsername}, reusing it`);
  }

  const repoFullName = `${githubUsername}/${projectName}`;
  const repoUrl = `https://github.com/${repoFullName}`;
  const cloneUrl = `https://github.com/${repoFullName}.git`;
  const authCloneUrl = `https://${githubAccessToken}@github.com/${repoFullName}.git`;

  logger.info(`Repo ready: ${repoUrl}`);

  // 2. Add a .gitignore to the scaffold dir if it doesn't have one
  const gitignorePath = path.join(scaffoldDir, ".gitignore");
  try {
    await fs.access(gitignorePath);
  } catch {
    await fs.writeFile(
      gitignorePath,
      "node_modules\ndist\n.env\n.env.local\n*.log\n",
    );
  }

  // 3. Add a README.md
  const readmePath = path.join(scaffoldDir, "README.md");
  try {
    await fs.access(readmePath);
  } catch {
    await fs.writeFile(
      readmePath,
      `# ${displayName}\n\n${description || "Generated by DuckOps."}\n\n## Getting started\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\`\n`,
    );
  }

  // 4. Git init, commit, and push
  const gitEnv = {
    ...process.env,
    GIT_AUTHOR_NAME: "DuckOps",
    GIT_AUTHOR_EMAIL: "duckops@noreply.github.com",
    GIT_COMMITTER_NAME: "DuckOps",
    GIT_COMMITTER_EMAIL: "duckops@noreply.github.com",
  };

  const run = (cmd: string) => execAsync(cmd, { cwd: scaffoldDir, env: gitEnv });

  // Remove any existing .git dir so we always start fresh
  await fs.rm(path.join(scaffoldDir, ".git"), { recursive: true, force: true });

  await run("git init -b main");
  await run("git add -A");

  // Commit only if there are staged changes
  const { stdout: statusOut } = await execAsync("git status --porcelain", { cwd: scaffoldDir, env: gitEnv });
  if (statusOut.trim()) {
    await run(`git commit -m "Initial scaffold generated by DuckOps"`);
  }

  await run(`git remote add origin ${authCloneUrl}`);
  await run("git push -u origin main --force");

  logger.info(`Code pushed to: ${repoUrl}`);

  return {
    repoUrl,
    repoName: projectName,
    repoFullName,
    cloneUrl,
  };
}

// Delete a GitHub repo (used when project is deleted)
export async function deleteRepo(
  repoFullName: string,
  githubAccessToken: string,
): Promise<void> {
  const res = await fetch(`${GITHUB_API}/repos/${repoFullName}`, {
    method: "DELETE",
    headers: {
      Authorization: `Bearer ${githubAccessToken}`,
      Accept: "application/vnd.github+json",
      "X-GitHub-Api-Version": "2022-11-28",
    },
  });

  if (!res.ok && res.status !== 404) {
    logger.warn(`Could not delete repo ${repoFullName}: ${res.statusText}`);
  } else {
    logger.info(`Deleted GitHub repo: ${repoFullName}`);
  }
}
