apiVersion: v1
kind: Service
metadata:
  name: provisioning-service
  namespace: duckops
spec:
  selector:
    app: provisioning-service
  ports:
    - protocol: TCP
      port: 4002
      targetPort: 4002
  type: ClusterIP
