import { createLogger } from "@duckops/shared-utils";

const logger = createLogger("jenkins-service");

const JENKINS_URL = process.env.JENKINS_URL || "http://localhost:8085";
const JENKINS_USER = process.env.JENKINS_USER || "admin";
const JENKINS_TOKEN = process.env.JENKINS_TOKEN || "";

const authHeader = JENKINS_TOKEN
  ? `Basic ${Buffer.from(`${JENKINS_USER}:${JENKINS_TOKEN}`).toString("base64")}`
  : "";

async function getCrumb(): Promise<Record<string, string>> {
  try {
    const headers: Record<string, string> = { "Content-Type": "application/json" };
    if (authHeader) headers.Authorization = authHeader;
    const res = await fetch(`${JENKINS_URL}/crumbIssuer/api/json`, { headers });
    if (!res.ok) return {};
    const data = await res.json() as { crumb: string; crumbRequestField: string };
    return { [data.crumbRequestField]: data.crumb };
  } catch {
    return {};
  }
}

async function upsertGitHubCredential(
  credentialId: string,
  username: string,
  token: string,
): Promise<void> {
  const credentialXml = `<com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl>
  <scope>GLOBAL</scope>
  <id>${credentialId}</id>
  <description>GitHub token for ${username} (auto-created by DuckOps)</description>
  <username>${username}</username>
  <password>${token}</password>
</com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl>`;

  const crumb = await getCrumb();

  // Try to update existing credential first
  const updateHeaders: Record<string, string> = {
    "Content-Type": "application/xml",
    ...crumb,
  };
  if (authHeader) updateHeaders.Authorization = authHeader;

  const updateRes = await fetch(
    `${JENKINS_URL}/credentials/store/system/domain/_/credential/${credentialId}/config.xml`,
    { method: "POST", headers: updateHeaders, body: credentialXml },
  );

  if (updateRes.ok) {
    logger.info(`Jenkins credential updated: ${credentialId}`);
    return;
  }

  // Credential doesn't exist yet — create it
  const createRes = await fetch(
    `${JENKINS_URL}/credentials/store/system/domain/_/createCredentials`,
    { method: "POST", headers: updateHeaders, body: credentialXml },
  );

  if (!createRes.ok && createRes.status !== 302) {
    const body = await createRes.text().catch(() => "");
    logger.warn(`Could not create Jenkins credential (${createRes.status}): ${body.slice(0, 200)}`);
  } else {
    logger.info(`Jenkins credential created: ${credentialId}`);
  }
}

export interface CreatePipelineConfig {
  projectName: string;
  gitRepoUrl: string;
  branch: string;
  githubUsername?: string;
  githubAccessToken?: string;
}

export interface JenkinsPipelineResult {
  jobName: string;
  jobUrl: string;
}

export async function createJenkinsPipeline(
  config: CreatePipelineConfig,
): Promise<JenkinsPipelineResult> {
  const jobName = `duckops-${config.projectName}`;
  const { projectName, gitRepoUrl, branch } = config;
  const registry = process.env.REGISTRY_URL || "k3d-duckops-registry:5111";
  const hostRegistry = process.env.HOST_REGISTRY_URL || "localhost:5111";
  const namespace = `project-${projectName}`;

  // Store GitHub token as a Jenkins credential so the pipeline can clone private repos
  const credentialId = `github-${config.githubUsername || "duckops"}`;
  if (config.githubUsername && config.githubAccessToken) {
    await upsertGitHubCredential(credentialId, config.githubUsername, config.githubAccessToken);
  }

  const jobConfigXml = `<?xml version='1.1' encoding='UTF-8'?>
<flow-definition plugin="workflow-job">
  <description>Auto-generated by DuckOps for ${projectName}</description>
  <triggers>
    <hudson.triggers.SCMTrigger>
      <spec>* * * * *</spec>
      <ignorePostCommitHooks>false</ignorePostCommitHooks>
    </hudson.triggers.SCMTrigger>
  </triggers>
  <definition class="org.jenkinsci.plugins.workflow.cps.CpsFlowDefinition" plugin="workflow-cps">
    <script>
pipeline {
    agent any

    environment {
        K8S_REGISTRY = '${registry}'
        HOST_REGISTRY = '${hostRegistry}'
        IMAGE_NAME = '${projectName}'
        NAMESPACE = '${namespace}'
        KUBECONFIG = '/root/.kube/config'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: '${branch}', url: '${gitRepoUrl}', credentialsId: '${credentialId}'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }

        stage('Run Tests') {
            steps {
                sh 'npm test || true'
            }
        }

        stage('Build Image') {
            steps {
                sh "docker build -t \${HOST_REGISTRY}/\${IMAGE_NAME}:\${BUILD_NUMBER} ."
                sh "docker tag \${HOST_REGISTRY}/\${IMAGE_NAME}:\${BUILD_NUMBER} \${HOST_REGISTRY}/\${IMAGE_NAME}:latest"
            }
        }

        stage('Push Image') {
            steps {
                sh "docker push \${HOST_REGISTRY}/\${IMAGE_NAME}:\${BUILD_NUMBER}"
                sh "docker push \${HOST_REGISTRY}/\${IMAGE_NAME}:latest"
            }
        }

        stage('Deploy') {
            steps {
                sh """
                    kubectl set image deployment/\${IMAGE_NAME} \\
                      \${IMAGE_NAME}=\${K8S_REGISTRY}/\${IMAGE_NAME}:\${BUILD_NUMBER} \\
                      -n \${NAMESPACE} --kubeconfig=\${KUBECONFIG}
                    kubectl rollout status deployment/\${IMAGE_NAME} -n \${NAMESPACE} --timeout=120s
                """
            }
        }
    }

    post {
        success { echo 'Deployment successful!' }
        failure { echo 'Deployment failed!' }
    }
}
    </script>
    <sandbox>true</sandbox>
  </definition>
</flow-definition>`;

  const crumb = await getCrumb();
  const createHeaders: Record<string, string> = {
    "Content-Type": "application/xml",
    ...crumb,
  };
  if (authHeader) createHeaders.Authorization = authHeader;

  // Delete existing job first if it exists (handles retry case)
  await fetch(`${JENKINS_URL}/job/${encodeURIComponent(jobName)}/doDelete`, {
    method: "POST",
    headers: { ...crumb, ...(authHeader ? { Authorization: authHeader } : {}) },
  }).catch(() => {});

  const response = await fetch(
    `${JENKINS_URL}/createItem?name=${encodeURIComponent(jobName)}`,
    {
      method: "POST",
      headers: createHeaders,
      body: jobConfigXml,
    },
  );

  if (!response.ok && response.status !== 400) {
    throw new Error(
      `Failed to create Jenkins job: ${response.status} ${response.statusText}`,
    );
  }

  logger.info(`Jenkins pipeline created: ${jobName}`);

  return {
    jobName,
    jobUrl: `${JENKINS_URL}/job/${encodeURIComponent(jobName)}`,
  };
}

export async function triggerBuild(jobName: string): Promise<void> {
  const crumb = await getCrumb();
  const headers: Record<string, string> = { ...crumb };
  if (authHeader) headers.Authorization = authHeader;

  const response = await fetch(
    `${JENKINS_URL}/job/${encodeURIComponent(jobName)}/build`,
    {
      method: "POST",
      headers,
    },
  );

  if (!response.ok) {
    throw new Error(
      `Failed to trigger build: ${response.status} ${response.statusText}`,
    );
  }

  logger.info(`Build triggered for: ${jobName}`);
}

export async function getBuildStatus(
  jobName: string,
  buildNumber: number,
): Promise<Record<string, unknown>> {
  const response = await fetch(
    `${JENKINS_URL}/job/${encodeURIComponent(jobName)}/${buildNumber}/api/json`,
    { headers: { Authorization: authHeader } },
  );

  if (!response.ok) {
    throw new Error(
      `Failed to get build status: ${response.status} ${response.statusText}`,
    );
  }

  return response.json() as Promise<Record<string, unknown>>;
}

export async function getLastBuildInfo(
  jobName: string,
): Promise<{ number: number; result: string; url: string } | null> {
  const response = await fetch(
    `${JENKINS_URL}/job/${encodeURIComponent(jobName)}/lastBuild/api/json`,
    { headers: { Authorization: authHeader } },
  );

  if (!response.ok) return null;
  return response.json() as any;
}

export interface BuildStage {
  id: string;
  name: string;
  status: "IN_PROGRESS" | "SUCCESS" | "FAILED" | "NOT_EXECUTED" | "PAUSED";
  durationMillis: number;
}

export interface LiveBuildInfo {
  building: boolean;
  number: number | null;
  result: string | null;
  url: string | null;
  stages: BuildStage[];
  consoleLines: string[];
  estimatedDurationMs: number;
  durationMs: number;
}

export async function getLiveBuildInfo(jobName: string): Promise<LiveBuildInfo> {
  const headers: Record<string, string> = {};
  if (authHeader) headers.Authorization = authHeader;

  // Get last build summary
  const buildRes = await fetch(
    `${JENKINS_URL}/job/${encodeURIComponent(jobName)}/lastBuild/api/json?tree=number,building,result,url,estimatedDuration,duration`,
    { headers },
  );

  if (!buildRes.ok) {
    return { building: false, number: null, result: null, url: null, stages: [], consoleLines: [], estimatedDurationMs: 0, durationMs: 0 };
  }

  const build = await buildRes.json() as {
    number: number; building: boolean; result: string | null;
    url: string; estimatedDuration: number; duration: number;
  };

  // Get stages via workflow API
  const stagesRes = await fetch(
    `${JENKINS_URL}/job/${encodeURIComponent(jobName)}/${build.number}/wfapi/describe`,
    { headers },
  ).catch(() => null);

  let stages: BuildStage[] = [];
  if (stagesRes?.ok) {
    const wf = await stagesRes.json() as { stages?: { id: string; name: string; status: string; durationMillis: number }[] };
    stages = (wf.stages || []).map((s) => ({
      id: s.id,
      name: s.name,
      status: s.status as BuildStage["status"],
      durationMillis: s.durationMillis,
    }));
  }

  // Get last 40 lines of console output
  const consoleRes = await fetch(
    `${JENKINS_URL}/job/${encodeURIComponent(jobName)}/${build.number}/consoleText`,
    { headers },
  ).catch(() => null);

  let consoleLines: string[] = [];
  if (consoleRes?.ok) {
    const text = await consoleRes.text();
    consoleLines = text.split("\n").filter(Boolean).slice(-40);
  }

  return {
    building: build.building,
    number: build.number,
    result: build.result,
    url: build.url,
    stages,
    consoleLines,
    estimatedDurationMs: build.estimatedDuration,
    durationMs: build.duration,
  };
}

export async function deleteJenkinsPipeline(jobName: string): Promise<void> {
  await fetch(
    `${JENKINS_URL}/job/${encodeURIComponent(jobName)}/doDelete`,
    {
      method: "POST",
      headers: { Authorization: authHeader },
    },
  );
  logger.info(`Jenkins pipeline deleted: ${jobName}`);
}
