FROM node:22-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
{{#if (eq orm "prisma")}}
RUN npx prisma generate
{{/if}}
RUN npm run build

FROM node:22-alpine AS runner

WORKDIR /app

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package*.json ./
{{#if (eq orm "prisma")}}
COPY --from=builder /app/prisma ./prisma
{{/if}}

EXPOSE {{port}}

CMD ["node", "dist/index.js"]
